name: xboost_system
description: "XBOOST SYSTEM Desktop Application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  qr_flutter: ^4.1.0
  sqflite: ^2.2.8
  sqflite_common_ffi: ^2.4.0
  path: ^1.9.1
  path_provider: ^2.0.15
  flutter_svg: ^2.0.7

flutter:
  uses-material-design: true
  assets:
    - assets/icons/xboost_logo.svg
    - assets/icons/xboost_logo_128.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
